name: flutter_map_animations
description: Animation utilities for markers and controls of the flutter_map package.
version: 0.6.0
homepage: https://github.com/TesteurManiak/flutter_map_animations
repository: https://github.com/TesteurManiak/flutter_map_animations
issue_tracker: https://github.com/TesteurManiak/flutter_map_animations/issues
screenshots:
  - description: Animated markers
    path: gifs/animated-marker.gif
  - description: Animated movement
    path: gifs/center-on-point.gif
  - description: Animated rotate
    path: gifs/rotate.gif
  - description: Animated zoom
    path: gifs/zoom.gif
funding:
  - https://www.buymeacoffee.com/guillaumeroux
topics:
  - flutter-map
  - map
  - animation

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  custom_lint: ">=0.5.11 <0.7.0"
  fd_lints: ^2.2.0
  flutter_test:
    sdk: flutter
